import { createFileRoute, Link } from '@tanstack/react-router';
import { useSuspenseQuery } from '@tanstack/react-query';
import { useState } from 'react';
import { Fingerprint, ChevronDown, ArrowRight, LockKeyhole, Check } from 'lucide-react';
import { AppShell, PrivacyLine, DemoNote } from '@/components/kin/shell';
import { Button } from '@/components/ui/button';
import { matchQuery, pageHead } from '@/lib/kin/queries';
export const Route = createFileRoute('/match/$id')({ head: () => pageHead('Possible KIN','Explore a possible connection with fictional ancestry signals. Identities remain hidden until mutual consent.'), loader: ({ context, params }) => context.queryClient.ensureQueryData(matchQuery(params.id)), component: MatchDetail });
function MatchDetail() {
  const { id } = Route.useParams();
  const { data: match } = useSuspenseQuery(matchQuery(id));
  const [expanded,setExpanded] = useState(false);
  return <AppShell back title="Possible KIN"><div className="narrow-page"><div className="text-center"><div className="mx-auto grid size-24 place-items-center rounded-full bg-primary/5 border border-primary/20 text-primary"><Fingerprint size={42} strokeWidth={1.2} /></div><p className="eyebrow text-primary mt-7">Maybe you’re not strangers.</p><h1 className="font-display text-4xl font-medium mt-4">Possible KIN</h1><p className="text-muted-foreground text-sm leading-relaxed mt-3 max-w-[330px] mx-auto">Someone nearby may share a family connection with you.</p></div><div className="mt-9 divide-y divide-border border-y border-border"><div className="flex justify-between py-5 gap-3 text-sm"><span className="text-muted-foreground">Possible relationship</span><span>{match.relationship}</span></div><div className="flex justify-between py-5 gap-3 text-sm"><span className="text-muted-foreground">Connection confidence</span><span className="text-primary font-semibold">{match.confidence}%</span></div><div className="flex justify-between py-5 gap-3 text-sm"><span className="text-muted-foreground">Approximate distance</span><span>{match.distance}</span></div></div><Button variant="ghost" className="w-full justify-between px-0 mt-3 h-12" onClick={() => setExpanded(!expanded)} aria-expanded={expanded}>Why this match? <ChevronDown className={expanded ? 'rotate-180' : ''} /></Button>{expanded && <div className="space-y-4 py-4 page-enter">{match.signals.map(signal => <div key={signal.id} className="flex gap-3"><Check size={14} className="shrink-0 text-primary mt-1" /><div><h3 className="text-xs font-medium">{signal.label}</h3><p className="text-xs text-muted-foreground leading-relaxed mt-1">{signal.description}</p></div></div>)}<p className="text-[10px] text-muted-foreground">Illustrative confidence only. No DNA analysis or genetic certainty.</p></div>}<div className="flex gap-2 text-[11px] text-muted-foreground mt-3"><LockKeyhole size={13} />Their identity is still private. So is yours.</div><Button asChild variant="kin" size="cta" className="w-full mt-8"><Link to="/reveal/$id" params={{ id }}>Explore connection <ArrowRight /></Link></Button><Button asChild variant="ghost" className="w-full mt-2 text-muted-foreground"><Link to="/discover">Not now</Link></Button><div className="mt-5"><PrivacyLine /></div><div className="mt-7"><DemoNote /></div></div></AppShell>;
}